name: CI-version

on:
    push:
        tags:
            - "v*"

jobs:
    tests:
        strategy:
            fail-fast: false
            matrix:
                os:
                    - ubuntu-latest
                    - macos-latest
                    - windows-latest
                node-version:
                    - 24.x
                    - 26.x
                toolchain:
                    - stable
                    - nightly
        name: Node ${{ matrix.node-version }} on ${{ matrix.os }} (Rust ${{ matrix.toolchain }})
        runs-on: ${{ matrix.os }}
        steps:
            - uses: actions/checkout@v7
            - uses: actions-rust-lang/setup-rust-toolchain@v2
              with:
                  toolchain: ${{ matrix.toolchain }}
            - uses: pnpm/action-setup@v6
              with:
                  version: 12.6.0
            - uses: actions/setup-node@v7
              with:
                  node-version: ${{ matrix.node-version }}
                  cache: pnpm
            - run: cargo test --release --locked
            - run: cargo doc --release --locked
            - run: pnpm install --frozen-lockfile
            - run: npm run build
            - run: npm test

    MSRV:
        strategy:
            fail-fast: false
            matrix:
                os:
                    - ubuntu-latest
                    - macos-latest
                    - windows-latest
        name: Rust 1.89 on ${{ matrix.os }}
        runs-on: ${{ matrix.os }}
        steps:
            - uses: actions/checkout@v7
            - uses: actions-rust-lang/setup-rust-toolchain@v2
              with:
                  toolchain: "1.89"
            - run: cargo test --release --lib --bins --locked
